# Generated by Django 4.2.19 on 2025-02-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userinfo_token_saveimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='年龄'),
        ),
    ]
